name: Golang CI/CD Pipeline

on:
  repository_dispatch:
    types: [ trigger-swe-go-common-shared ]
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  verify-go-library:
    name: Verify Go Library
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        go-version: [ '1.22.x', '1.23.x' ]

    env:
      CACHE_PATHS: |
        ~/.cache/go-build
        ~/go/pkg/mod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download
          go list -m all  # Ensure dependencies are correctly resolved

      - name: Verify Go Environment
        run: |
          go version
          go env

      - name: Check Code Formatting
        run: go fmt ./...

      - name: Run Vet (Static Analysis)
        run: go vet ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Update protobuf
        run: |
          chmod +x ./scripts/update_protobuf.sh
          ./scripts/update_protobuf.sh
        shell: bash

      - name: Commit and push changes
        run: |
          git config --global user.name "ngdangkietse"
          git config --global user.email "kietnguyen17052001@gmail.com"
          if [ -n "$(git status -s)" ]; then
            git status
            git add .
            git commit -m "chore: regenerate files"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}